version: "3.8"
services:
  server:
    restart: always
    platform: linux/amd64
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    container_name: server
    hostname: server
    volumes:
      - ./:/app/
      # Prevents the host node_modules from clobbering the image's
      - /app/node_modules
    ports:
      - 8006:8006
  client:
    restart: always
    platform: linux/amd64
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    volumes:
      - ./:/app/
      # Prevents the host node_modules from clobbering the image's
      - /app/node_modules
    ports:
      - 8080:8080
