version: "3.8"
services:
  server:
    restart: always
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    volumes:
      - ./:/app
      # Prevents the host node_modules from clobbering the image's
      - /app/node_modules
    ports:
      - 8006:8006
  client:
    restart: always
    depends_on:
    - "server"
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    volumes:
      - ./:/usr/share/nginx/html/
      # Prevents the host node_modules from clobbering the image's
      - /app/node_modules
    ports:
      - 8080:8080
